name = "x-fav-front"
pages_build_output_dir = "./dist"
compatibility_date = "2024-06-13"

[[d1_databases]]
binding = "DB"
database_name = "x-fav"
migrations_dir="drizzle/migrations"
database_id="$database_id"
